api_platform:
    title: Hello API Platform
    version: 1.0.0

    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]

    formats:
        jsonld: [ 'application/ld+json' ]
        multipart: [ 'multipart/form-data' ]

    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    patch_formats:
        json: ['application/merge-patch+json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

    keep_legacy_inflector: false

    use_symfony_listeners: true

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
